### ISSUE TITLE
HTTPS on http://app-mtmm.rubenwardy.com/

### ISSUE THREAD

**Issue by rugk** [rubenwardy/mtmods4android#31]
You should really add HTTPS to your mod manager. Use letsencrypt.org.

This is the easiest way to secure your downloads. I don't know if you currently do any verification of the downloaded files.

**Comment by rubenwardy** [comment]
I'm planning on only allowing github or bitbucket links (to start with), making downloads point to a particular commit which is virus scanned, and running checksums. Currently no verification is done on the downloaded files. Files are currently downloaded directly from their source, not from my website. Hence the disclaimer

**Comment by rugk** [comment]
Ah so your website actually is not the download location? You should add HTTPS anyway, but it is at least not so serious in this case.

So what about the source downloads? Do they use HTTPS?
If the files are downloaded from GitHub, do you honor their HPKP header?

**Comment by rubenwardy** [comment]
Anything from Github is downloaded over https, I'm not sure what HPKP is

**Comment by rugk** [comment]
See https://scotthelme.co.uk/hpkp-http-public-key-pinning/

**Comment by rubenwardy** [comment]
1342849
