### ISSUE TITLE
Displaying screenshot of a different mod

### ISSUE THREAD

**Issue by LNJ2** [rubenwardy/mtmods4android#33]
The screenshot displayed here is of https://github.com/minetest-mods/lapis, but it's using the wrong `lapis` mod (there are two with that name). I can only find _this_ mod (not a second).

![photo_2017-04-16_20-44-53](https://cloud.githubusercontent.com/assets/13557034/25073377/af22af1a-22e5-11e7-8f30-b95dcd5832d2.jpg)

**Comment by rubenwardy** [comment]
You're using quite an old version - 1.4.0 or older - we're now on 1.6.0

**Comment by LNJ2** [comment]
Oh sorry, I just have used the version from F-Droid.
