### ISSUE TITLE
Error on receiving mods

### ISSUE THREAD

**Issue by ghost** [rubenwardy/mtmods4android#40]
I don't know which error, it never says. Only it can't download the mod list.
(Yes, the device is connected to the internet, Chromium functions very well with this site)

What I tried:
Reinstalling the APK. Trying the one from F-Droid, from APK Pure and the latest one (1.8.0) from this site.
Adding mods manually it shows this mods and I can activate them.

Hardware:
Samsung Galaxy Tab 3 (SM-T210),
Android 4.4.2 with custom rom and removed Google apps

**Comment by kaeptmblaubaer1000** [comment]
On my device too, it's an SSL error.
@rubenwardy have you recently changed something on your server configuration? Like GitHub which recently dropped TLSv1 support? On older Android versions newer versions of TLS are disabled by default.

**Comment by rubenwardy** [comment]
Pushed a new update that may fix this, please check it out :)
