### ISSUE TITLE
Expected :status header not present

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/mtmods4android#42]
OnePlus 5, Android 8.1.0.  Happy to help debug in any way I can.

![image](https://user-images.githubusercontent.com/2122943/51209978-7cc20180-1909-11e9-84ea-6e377759260f.png)

**Comment by rakshazi** [comment]
Same here

**Comment by rubenwardy** [comment]
I've released a new version which should fix this. Please let me know if it does
